on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

name: tests

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.18.x]
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v3

    - name: Run go test
      run: go test -v -race -covermode atomic ./...
